export const alternativeNames = {
  'United States': ['United States of America', 'USA'],
  'Antigua and Barbuda': ['Antigua'],
  'United Kingdom': ['UK', 'Great Britain', 'England', 'Britain'],
  'Congo [DRC]': ['Democratic Republic of the Congo', 'Congo Dem. Republic of'],
  'Congo [Republic]': ['Republic of the Congo', 'Congo Republic of'],
  'Côte d\'Ivoire': ['Ivory Coast', 'Côte d’Ivoire'],
  'Falkland Islands [Islas Malvinas]': ['Falkland Islands'],
  'South Korea': ['Korea, South', 'Korea Republic of'],
  'Macau': ['Macao'],
  'Azores': ['Azores Islands'],
  'Madeira': ['Madera'],
  'Myanmar [Burma]': ['Myanmar'],
  'Macedonia [FYROM]': ['Macedonia', 'North Macedonia'],
  'Micronesia': ['Chuuk'],
  'Saint Helena': ['St. Helena'],
  'Saint Lucia': ['St. Lucia'],
  'Saint Pierre and Miquelon': ['St. Pierre and Miquelon'],
  'Saint Vincent and the Grenadines': ['St. Vincent and the Grenadines', 'St. Vincent & the Grenadines'],
  'Sudan': ['South Sudan'],
  'French Polynesia': ['Tahiti'],
  'Northern Mariana Islands': ['Tinian'],
  'Trinidad and Tobago': ['Trinidad', 'Trinidad & Tobago'],
  'Turks and Caicos Islands': ['Turks and Caicos'],
  'U.S. Virgin Islands': ['US Virgin Islands', 'Virgin Islands U.S.'],
  'British Virgin Islands': ['Virgin Islands British'],
  'Wallis and Futuna': ['Wallis & Futuna', 'Wallis & Futuna Islands'],
  'Swaziland': ["Eswatini"]
}
